export type { VdgAssetProps } from "../shared/types";
export * from "./HeroBackground";
export * from "./DashboardBackground";
export * from "./AuthenticationBackground";
export * from "./WorkflowBackground";
export * from "./CitizenPortalBackground";
export * from "./BusinessPortalBackground";
export * from "./OfficerPortalBackground";
export * from "./AdminPortalBackground";
export * from "./SearchBackground";
export * from "./ReportsBackground";
export * from "./AIAssistantBackground";
export * from "./EmptyStateBackground";
export * from "./NotFoundBackground";
export * from "./ServerErrorBackground";
export * from "./SuccessBackground";
export * from "./WarningBackground";
export * from "./MaintenanceBackground";
