export * from "./Header";
export * from "./Footer";
export * from "./Sidebar";
export * from "./LandingPage";
export * from "./CitizenDashboardPage";
export * from "./BusinessDashboardPage";
export * from "./OfficerDashboardPage";
export * from "./CaseDetailPage";
export * from "./AuthPage";
export * from "./MfaPage";
export * from "./ForgotPasswordPage";
export * from "./RegisterLandingPage";
export * from "./CitizenRegisterPage";
export * from "./BusinessRegisterPage";
export * from "./RegisterOtpPage";
export * from "./RegisterSuccessPage";
export * from "./ProfilePage";
export * from "./SettingsPage";
export * from "./NotificationsPage";
export * from "./HelpCenterPage";
export * from "./LegalPage";
export * from "./ErrorStatusPage";
export * from "./SearchResultsPage";
export * from "./WorkflowTimeline";
export * from "./AIAssistantPanel";
export type { Screen, Portal, LegalDoc, ErrorType, RegisterAccountType } from "./navigation";
export { t, dictionary, type Locale, type DictionaryKey } from "./i18n";
